// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project420.Cultivation.DAL;

#nullable disable

namespace Project420.Cultivation.DAL.Migrations
{
    [DbContext(typeof(CultivationDbContext))]
    partial class CultivationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project420.Cultivation.Models.Entities.GrowCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualHarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CycleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrowRoomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("PlannedHarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantsHarvested")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StrainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TotalDryWeightGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalPlantsStarted")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalWetWeightGrams")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CycleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_GrowCycles_CycleCode");

                    b.HasIndex("GrowRoomId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_GrowCycles_IsActive");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_GrowCycles_StartDate");

                    b.HasIndex("StrainName")
                        .HasDatabaseName("IX_GrowCycles_StrainName");

                    b.ToTable("GrowCycles");
                });

            modelBuilder.Entity("Project420.Cultivation.Models.Entities.GrowRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LightCycle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("RoomSizeSquareMeters")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.Property<string>("TargetHumidity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetTemperature")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_GrowRooms_IsActive");

                    b.HasIndex("RoomCode")
                        .IsUnique()
                        .HasDatabaseName("IX_GrowRooms_RoomCode");

                    b.HasIndex("RoomType")
                        .HasDatabaseName("IX_GrowRooms_RoomType");

                    b.ToTable("GrowRooms");
                });

            modelBuilder.Entity("Project420.Cultivation.Models.Entities.HarvestBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CBDPercentage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CureDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrowCycleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabTestCertificateNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LabTestDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("LabTestPassed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PlantCount")
                        .HasColumnType("int");

                    b.Property<string>("ProcessingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StrainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("THCPercentage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TotalDryWeightGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWetWeightGrams")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_HarvestBatches_BatchNumber");

                    b.HasIndex("GrowCycleId")
                        .HasDatabaseName("IX_HarvestBatches_GrowCycleId");

                    b.HasIndex("HarvestDate")
                        .HasDatabaseName("IX_HarvestBatches_HarvestDate");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_HarvestBatches_IsActive");

                    b.HasIndex("StrainName")
                        .HasDatabaseName("IX_HarvestBatches_StrainName");

                    b.ToTable("HarvestBatches");
                });

            modelBuilder.Entity("Project420.Cultivation.Models.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CurrentGrowRoomId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DestroyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestructionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DryWeightGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GrowCycleId")
                        .HasColumnType("int");

                    b.Property<int?>("HarvestBatchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MotherPlantId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PlantSex")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PlantSource")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PlantTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PlantedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StageStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StrainName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("WasteWeightGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WetWeightGrams")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentGrowRoomId")
                        .HasDatabaseName("IX_Plants_CurrentGrowRoomId");

                    b.HasIndex("CurrentStage")
                        .HasDatabaseName("IX_Plants_CurrentStage");

                    b.HasIndex("GrowCycleId")
                        .HasDatabaseName("IX_Plants_GrowCycleId");

                    b.HasIndex("HarvestBatchId")
                        .HasDatabaseName("IX_Plants_HarvestBatchId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Plants_IsActive");

                    b.HasIndex("MotherPlantId");

                    b.HasIndex("PlantTag")
                        .IsUnique()
                        .HasDatabaseName("IX_Plants_PlantTag");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Project420.Cultivation.Models.Entities.GrowCycle", b =>
                {
                    b.HasOne("Project420.Cultivation.Models.Entities.GrowRoom", "GrowRoom")
                        .WithMany("GrowCycles")
                        .HasForeignKey("GrowRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GrowRoom");
                });

            modelBuilder.Entity("Project420.Cultivation.Models.Entities.HarvestBatch", b =>
                {
                    b.HasOne("Project420.Cultivation.Models.Entities.GrowCycle", "GrowCycle")
                        .WithMany("HarvestBatches")
                        .HasForeignKey("GrowCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrowCycle");
                });

            modelBuilder.Entity("Project420.Cultivation.Models.Entities.Plant", b =>
                {
                    b.HasOne("Project420.Cultivation.Models.Entities.GrowRoom", "CurrentGrowRoom")
                        .WithMany("Plants")
                        .HasForeignKey("CurrentGrowRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project420.Cultivation.Models.Entities.GrowCycle", "GrowCycle")
                        .WithMany("Plants")
                        .HasForeignKey("GrowCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project420.Cultivation.Models.Entities.HarvestBatch", "HarvestBatch")
                        .WithMany("Plants")
                        .HasForeignKey("HarvestBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project420.Cultivation.Models.Entities.Plant", "MotherPlant")
                        .WithMany()
                        .HasForeignKey("MotherPlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentGrowRoom");

                    b.Navigation("GrowCycle");

                    b.Navigation("HarvestBatch");

                    b.Navigation("MotherPlant");
                });

            modelBuilder.Entity("Project420.Cultivation.Models.Entities.GrowCycle", b =>
                {
                    b.Navigation("HarvestBatches");

                    b.Navigation("Plants");
                });

            modelBuilder.Entity("Project420.Cultivation.Models.Entities.GrowRoom", b =>
                {
                    b.Navigation("GrowCycles");

                    b.Navigation("Plants");
                });

            modelBuilder.Entity("Project420.Cultivation.Models.Entities.HarvestBatch", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
