// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project420.Shared.Database;

#nullable disable

namespace Project420.Shared.Database.Migrations
{
    [DbContext(typeof(SharedDbContext))]
    partial class SharedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project420.Shared.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OldValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("IX_AuditLogs_ActionType");

                    b.HasIndex("Module")
                        .HasDatabaseName("IX_AuditLogs_Module");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_AuditLogs_OccurredAt");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_AuditLogs_Severity");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_Entity");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("IX_AuditLogs_Entity_Date");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Project420.Shared.Core.Entities.ErrorLog", b =>
                {
                    b.Property<int>("ErrorLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorLogId"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InnerException")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ErrorLogId");

                    b.HasIndex("IsResolved")
                        .HasDatabaseName("IX_ErrorLogs_IsResolved");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_ErrorLogs_OccurredAt");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_ErrorLogs_Severity");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_ErrorLogs_Source");

                    b.HasIndex("IsResolved", "Severity", "OccurredAt")
                        .HasDatabaseName("IX_ErrorLogs_Resolved_Severity_Date");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("Project420.Shared.Core.Entities.StationConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccessExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EncryptedConnectionString")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccessExpiresAt")
                        .HasDatabaseName("IX_StationConnections_AccessExpiresAt");

                    b.HasIndex("DatabaseName")
                        .HasDatabaseName("IX_StationConnections_DatabaseName");

                    b.HasIndex("HostName")
                        .HasDatabaseName("IX_StationConnections_HostName");

                    b.HasIndex("IsAuthorized")
                        .HasDatabaseName("IX_StationConnections_IsAuthorized");

                    b.HasIndex("HostName", "IsAuthorized")
                        .HasDatabaseName("IX_StationConnections_HostName_IsAuthorized");

                    b.ToTable("StationConnections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Project420 - Main Store",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            DatabaseName = "Project420_Dev",
                            EncryptedConnectionString = "Server=JASON\\SQLDEVED;Database=Project420_Dev;User Id=sa;Password=ZAQxsw123;TrustServerCertificate=True;",
                            HostName = "POS-STORE-01",
                            IsAuthorized = true,
                            IsDeleted = false,
                            Notes = "Main POS terminal for Store 01"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Project420 - Branch Store",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            DatabaseName = "Project420_Dev2",
                            EncryptedConnectionString = "Server=JASON\\SQLDEVED;Database=Project420_Dev2;User Id=sa;Password=ZAQxsw123;TrustServerCertificate=True;",
                            HostName = "POS-STORE-01",
                            IsAuthorized = true,
                            IsDeleted = false,
                            Notes = "Backup access to Branch Store for emergencies"
                        },
                        new
                        {
                            Id = 3,
                            AccessExpiresAt = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            CompanyName = "Project420 - Main Store",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            DatabaseName = "Project420_Dev",
                            EncryptedConnectionString = "Server=JASON\\SQLDEVED;Database=Project420_Dev;User Id=sa;Password=ZAQxsw123;TrustServerCertificate=True;",
                            HostName = "MOBILE-REP-01",
                            IsAuthorized = true,
                            IsDeleted = false,
                            Notes = "Regional manager tablet - temporary access for Q4 2025"
                        });
                });

            modelBuilder.Entity("Project420.Shared.Core.Entities.TransactionNumberSequence", b =>
                {
                    b.Property<int>("SequenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SequenceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CurrentSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaddingLength")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("StartingSequence")
                        .HasColumnType("bigint");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("SequenceId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TransactionNumberSequences_IsActive");

                    b.HasIndex("LastGeneratedAt")
                        .HasDatabaseName("IX_TransactionNumberSequences_LastGeneratedAt");

                    b.HasIndex("TransactionType")
                        .IsUnique()
                        .HasDatabaseName("IX_TransactionNumberSequences_TransactionType_Unique");

                    b.ToTable("TransactionNumberSequences");

                    b.HasData(
                        new
                        {
                            SequenceId = 1,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            CurrentSequence = 0L,
                            Description = "Sales invoices - formal account invoices",
                            IsActive = true,
                            PaddingLength = 5,
                            Prefix = "INV",
                            StartingSequence = 1L,
                            TransactionType = 4
                        },
                        new
                        {
                            SequenceId = 2,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            CurrentSequence = 0L,
                            Description = "Credit notes - refunds and returns",
                            IsActive = true,
                            PaddingLength = 5,
                            Prefix = "CRN",
                            StartingSequence = 1L,
                            TransactionType = 5
                        },
                        new
                        {
                            SequenceId = 3,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            CurrentSequence = 0L,
                            Description = "Point of Sale transactions - retail sales",
                            IsActive = true,
                            PaddingLength = 5,
                            Prefix = "",
                            StartingSequence = 1L,
                            TransactionType = 1
                        },
                        new
                        {
                            SequenceId = 4,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            CurrentSequence = 0L,
                            Description = "Goods received notes - stock received from suppliers",
                            IsActive = true,
                            PaddingLength = 5,
                            Prefix = "GRV",
                            StartingSequence = 1L,
                            TransactionType = 2
                        },
                        new
                        {
                            SequenceId = 5,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            CurrentSequence = 0L,
                            Description = "Returns to supplier - defective/unwanted stock",
                            IsActive = true,
                            PaddingLength = 5,
                            Prefix = "RTS",
                            StartingSequence = 1L,
                            TransactionType = 3
                        },
                        new
                        {
                            SequenceId = 6,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            CurrentSequence = 0L,
                            Description = "Stock adjustments - internal corrections",
                            IsActive = true,
                            PaddingLength = 5,
                            Prefix = "ADJ",
                            StartingSequence = 1L,
                            TransactionType = 6
                        },
                        new
                        {
                            SequenceId = 7,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            CurrentSequence = 0L,
                            Description = "Customer payments - cash/card/EFT received",
                            IsActive = true,
                            PaddingLength = 5,
                            Prefix = "PAY",
                            StartingSequence = 1L,
                            TransactionType = 7
                        },
                        new
                        {
                            SequenceId = 8,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            CurrentSequence = 0L,
                            Description = "Sales quotations - non-binding estimates",
                            IsActive = true,
                            PaddingLength = 5,
                            Prefix = "QTE",
                            StartingSequence = 1L,
                            TransactionType = 8
                        },
                        new
                        {
                            SequenceId = 9,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            CurrentSequence = 0L,
                            Description = "Layby transactions - deposit for future collection",
                            IsActive = true,
                            PaddingLength = 5,
                            Prefix = "LAY",
                            StartingSequence = 1L,
                            TransactionType = 9
                        },
                        new
                        {
                            SequenceId = 10,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            CurrentSequence = 0L,
                            Description = "Stock transfers - inter-location movements",
                            IsActive = true,
                            PaddingLength = 5,
                            Prefix = "TRF",
                            StartingSequence = 1L,
                            TransactionType = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
