using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Project420.Shared.Core.Entities;

namespace Project420.Management.Models.Entities.SystemAdministration
{
    /// <summary>
    /// Represents HR/administrative data for a system user (extends User entity)
    /// </summary>
    /// <remarks>
    /// Architecture Decision: Split User Concerns
    ///
    /// User (Shared.Core):
    /// - WHO you are: Username, Password, Email
    /// - Authentication and basic identity
    /// - Referenced by ALL modules for user identity
    ///
    /// UserProfile (Management.Models):
    /// - ADMINISTRATIVE data: Employee number, department, compliance
    /// - HR and employment information
    /// - Only referenced by Management/Admin modules
    ///
    /// Benefits:
    /// - Retail.POS can identify cashiers without referencing Management module
    /// - Clean dependency flow: Operational → Shared.Core (not → Management)
    /// - Management module extends User with HR features
    /// - No circular dependencies
    ///
    /// Relationship:
    /// - One User : One UserProfile (1:1)
    /// - UserProfile.UserId → User.Id (foreign key)
    /// - Not all Users need UserProfile (API users, service accounts)
    ///
    /// Cannabis Compliance Requirements (SA Cannabis for Private Purposes Act 2024):
    /// - Background checks required for cannabis handlers (SAHPRA requirement)
    /// - Staff training certification tracking
    /// - License verification for certain roles (pharmacists, cultivators)
    /// - Activity logging for compliance audits
    ///
    /// POPIA Compliance (CRITICAL - R10 MILLION PENALTY):
    /// - Employment data is PII (Personally Identifiable Information)
    /// - ID number, phone must be protected and encrypted at rest
    /// - 3-year retention requirement AFTER employment termination
    /// - Use soft delete (IsDeleted in AuditableEntity)
    /// - Employee consent required for data collection
    /// - Employee has right to access and correct their data
    ///
    /// Usage:
    /// <code>
    /// // Get user identity (any module can do this)
    /// var user = await _userRepo.GetByIdAsync(userId);
    /// Console.WriteLine($"Logged in: {user.FullName}");
    ///
    /// // Get HR details (Management module only)
    /// var profile = await _userProfileRepo.GetByUserIdAsync(userId);
    /// Console.WriteLine($"Employee #: {profile.EmployeeNumber}");
    /// Console.WriteLine($"Background check: {profile.BackgroundCheckStatus}");
    /// </code>
    /// </remarks>
    public class UserProfile : AuditableEntity
    {
        // ============================================================
        // RELATIONSHIP TO USER (1:1)
        // ============================================================

        /// <summary>
        /// Foreign key to User entity (authentication/identity)
        /// </summary>
        /// <remarks>
        /// One UserProfile per User
        /// Links HR data to authentication identity
        /// Cascade delete: If User deleted, delete UserProfile
        /// </remarks>
        [Required]
        [Display(Name = "User ID")]
        public int UserId { get; set; }

        // ============================================================
        // EMPLOYMENT INFORMATION
        // ============================================================

        /// <summary>
        /// Employee number (unique identifier for HR/payroll purposes)
        /// </summary>
        /// <remarks>
        /// Different from User.Id and database Id
        /// This is the HR/payroll reference number
        ///
        /// Examples: "EMP-0001", "E12345", "2025-001"
        ///
        /// Should be unique across the organization
        /// Generated by HR system or manually assigned
        /// </remarks>
        [MaxLength(50)]
        [Display(Name = "Employee Number")]
        public string? EmployeeNumber { get; set; }

        /// <summary>
        /// South African ID number (for payroll, tax, compliance)
        /// </summary>
        /// <remarks>
        /// POPIA: This is SENSITIVE PII - MUST be encrypted in production
        ///
        /// Required for:
        /// - Payroll processing
        /// - Tax reporting (SARS)
        /// - Background checks (cannabis industry requirement)
        /// - Employment verification
        ///
        /// SA ID Number format: YYMMDD SSSS C AZ
        /// Can derive date of birth and gender from ID number
        /// </remarks>
        [MaxLength(20)]
        [Display(Name = "ID Number")]
        public string? IdNumber { get; set; }

        /// <summary>
        /// Employee's phone number (work/mobile)
        /// </summary>
        /// <remarks>
        /// POPIA: This is PII - encrypt at rest in production
        /// Format: South African numbers typically +27 XX XXX XXXX
        ///
        /// Used for:
        /// - Emergency contact
        /// - Work notifications
        /// - Shift reminders
        /// </remarks>
        [MaxLength(20)]
        [Phone(ErrorMessage = "Invalid phone number format")]
        [Display(Name = "Phone Number")]
        public string? PhoneNumber { get; set; }

        /// <summary>
        /// Department or division where employee works
        /// </summary>
        /// <remarks>
        /// Examples:
        /// - "Sales"
        /// - "Cultivation"
        /// - "Production"
        /// - "Administration"
        /// - "Finance"
        ///
        /// Used for:
        /// - Organizational reporting
        /// - Access control policies
        /// - Department-specific analytics
        /// </remarks>
        [MaxLength(100)]
        [Display(Name = "Department")]
        public string? Department { get; set; }

        /// <summary>
        /// Job title or position
        /// </summary>
        /// <remarks>
        /// Examples:
        /// - "Store Manager"
        /// - "Senior Cultivator"
        /// - "Cashier"
        /// - "System Administrator"
        /// - "Quality Control Specialist"
        ///
        /// May influence:
        /// - Default permissions/role
        /// - Salary grade
        /// - Reporting structure
        /// </remarks>
        [MaxLength(100)]
        [Display(Name = "Position/Title")]
        public string? Position { get; set; }

        /// <summary>
        /// Date when employee started working
        /// </summary>
        /// <remarks>
        /// Used for:
        /// - Seniority calculations
        /// - Probation period tracking
        /// - Anniversary recognition
        /// - Service leave accrual
        /// </remarks>
        [Display(Name = "Employment Start Date")]
        public DateTime? EmploymentStartDate { get; set; }

        /// <summary>
        /// Date when employee left/terminated (if applicable)
        /// </summary>
        /// <remarks>
        /// POPIA: Retain employment records for 3 years after termination
        /// Use IsDeleted (AuditableEntity) for soft delete
        /// Set this date when terminating employment
        ///
        /// After 3 years: System can permanently purge (with proper process)
        /// </remarks>
        [Display(Name = "Employment End Date")]
        public DateTime? EmploymentEndDate { get; set; }

        /// <summary>
        /// Whether employee is currently employed
        /// </summary>
        /// <remarks>
        /// Computed based on EmploymentEndDate:
        /// - true: EmploymentEndDate is null
        /// - false: EmploymentEndDate is set
        ///
        /// Used for filtering active employees
        /// </remarks>
        [NotMapped]
        [Display(Name = "Is Currently Employed")]
        public bool IsCurrentlyEmployed => EmploymentEndDate == null;

        // ============================================================
        // CANNABIS COMPLIANCE (SA Specific)
        // ============================================================

        /// <summary>
        /// Background check status (required for cannabis handlers)
        /// </summary>
        /// <remarks>
        /// Cannabis Compliance: SAHPRA requires background checks for:
        /// - Anyone handling cannabis products
        /// - Access to cultivation areas
        /// - Inventory management
        /// - Sales staff
        ///
        /// Status values:
        /// - "Pending" - Check in progress
        /// - "Cleared" - Passed background check
        /// - "Failed" - Did not pass
        /// - "Expired" - Check needs renewal
        /// - null - Not yet initiated
        ///
        /// Must be renewed annually
        /// </remarks>
        [MaxLength(50)]
        [Display(Name = "Background Check Status")]
        public string? BackgroundCheckStatus { get; set; }

        /// <summary>
        /// Date when background check was completed
        /// </summary>
        [Display(Name = "Background Check Date")]
        public DateTime? BackgroundCheckDate { get; set; }

        /// <summary>
        /// Date when background check expires (typically 1 year)
        /// </summary>
        /// <remarks>
        /// Alert system:
        /// - 90 days before expiry: Notify HR to schedule renewal
        /// - 60 days: Notify employee and manager
        /// - 30 days: Escalate to admin
        /// - Expired: Restrict access to cannabis handling modules
        /// </remarks>
        [Display(Name = "Background Check Expiry")]
        public DateTime? BackgroundCheckExpiryDate { get; set; }

        /// <summary>
        /// Cannabis handling license number (if applicable)
        /// </summary>
        /// <remarks>
        /// Required for certain roles:
        /// - Pharmacists: Section 22A permit (SAHPRA)
        /// - Cultivation supervisors: DALRRD permit
        /// - Quality control: SAHPRA certification
        /// - Production managers: GMP certification
        ///
        /// Not all employees need this - only those in specialized roles
        /// </remarks>
        [MaxLength(100)]
        [Display(Name = "Cannabis License Number")]
        public string? CannabisLicenseNumber { get; set; }

        /// <summary>
        /// Type of cannabis license held
        /// </summary>
        /// <remarks>
        /// Examples:
        /// - "SAHPRA_Section22A" - Medical cannabis dispensing
        /// - "SAHPRA_Section22C" - Cannabis product handling
        /// - "DALRRD_Cultivation" - Cultivation permit
        /// - "GMP_Production" - Good Manufacturing Practice
        ///
        /// Used to verify module access permissions
        /// Plantation module requires DALRRD_Cultivation
        /// Production module requires GMP_Production
        /// </remarks>
        [MaxLength(100)]
        [Display(Name = "Cannabis License Type")]
        public string? CannabisLicenseType { get; set; }

        /// <summary>
        /// Expiry date of cannabis handling license
        /// </summary>
        /// <remarks>
        /// Alert system similar to background checks
        /// System restricts module access if license expires
        /// </remarks>
        [Display(Name = "Cannabis License Expiry")]
        public DateTime? CannabisLicenseExpiryDate { get; set; }

        /// <summary>
        /// Date when compliance training was completed
        /// </summary>
        /// <remarks>
        /// All staff must complete:
        /// - Cannabis Act 2024 overview
        /// - POPIA data protection training
        /// - Company policies and procedures
        /// - Safety and handling procedures
        /// - Role-specific training
        ///
        /// Required before accessing any cannabis modules
        /// </remarks>
        [Display(Name = "Compliance Training Date")]
        public DateTime? ComplianceTrainingDate { get; set; }

        /// <summary>
        /// Date when compliance training expires (typically 1 year)
        /// </summary>
        /// <remarks>
        /// Annual refresher training required
        /// System alerts and restricts access if expired
        /// </remarks>
        [Display(Name = "Compliance Training Expiry")]
        public DateTime? ComplianceTrainingExpiryDate { get; set; }

        // ============================================================
        // EMERGENCY CONTACT (POPIA Protected)
        // ============================================================

        /// <summary>
        /// Emergency contact person name
        /// </summary>
        /// <remarks>
        /// POPIA: Emergency contact data is PII of a third party
        /// Requires employee consent to collect
        /// Encrypted at rest
        /// Only accessible to HR and in emergencies
        /// </remarks>
        [MaxLength(200)]
        [Display(Name = "Emergency Contact Name")]
        public string? EmergencyContactName { get; set; }

        /// <summary>
        /// Emergency contact phone number
        /// </summary>
        /// <remarks>
        /// POPIA: Third-party PII - encrypt at rest
        /// </remarks>
        [MaxLength(20)]
        [Phone(ErrorMessage = "Invalid phone number format")]
        [Display(Name = "Emergency Contact Phone")]
        public string? EmergencyContactPhone { get; set; }

        /// <summary>
        /// Relationship to emergency contact
        /// </summary>
        /// <remarks>
        /// Examples: "Spouse", "Parent", "Sibling", "Friend"
        /// </remarks>
        [MaxLength(50)]
        [Display(Name = "Emergency Contact Relationship")]
        public string? EmergencyContactRelationship { get; set; }

        // ============================================================
        // HR NOTES & ADDITIONAL INFO
        // ============================================================

        /// <summary>
        /// Internal HR notes about this employee
        /// </summary>
        /// <remarks>
        /// Use for:
        /// - Performance notes
        /// - Training requirements
        /// - Accommodation needs
        /// - Special circumstances
        ///
        /// CRITICAL WARNING (POPIA):
        /// - Be extremely careful what is recorded here
        /// - Avoid sensitive personal opinions
        /// - No discriminatory information
        /// - No medical information (unless relevant to accommodation)
        /// - These notes may be subject to employee access requests
        /// - May be discoverable in legal proceedings
        ///
        /// Best Practice:
        /// - Keep notes factual and objective
        /// - Focus on job-related matters only
        /// - Assume employee will read these notes
        /// </remarks>
        [MaxLength(2000)]
        [Display(Name = "HR Notes")]
        public string? HRNotes { get; set; }

        // ============================================================
        // NAVIGATION PROPERTIES (EF Core Relationships)
        // ============================================================

        /// <summary>
        /// Navigation property to User entity (authentication/identity)
        /// </summary>
        /// <remarks>
        /// One-to-one relationship
        /// Allows accessing User data from UserProfile:
        /// <code>
        /// var profile = await _db.UserProfiles
        ///     .Include(up => up.User)
        ///     .FirstAsync(up => up.UserId == userId);
        ///
        /// Console.WriteLine($"Username: {profile.User.Username}");
        /// Console.WriteLine($"Employee#: {profile.EmployeeNumber}");
        /// </code>
        /// </remarks>
        [ForeignKey(nameof(UserId))]
        public virtual User? User { get; set; }
    }
}
